#!/bin/sh
module="memdev"
device="memdev"
mode="777"

# 加载模块
/sbin/insmod ./$module.o $* || exit 1

#查询设备号
major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

# 创建设备节点
rm -f /dev/${device}[0-2]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
 
chmod $mode  /dev/${device}[0-2]






